# ProgrammingProject3_MHZ
---
**Author:** Haziq Zed 
**Version:** 1.0  
**Semester:** Fall 2020  

This *notebook* contains my solution to **ProgrammingProject3_MHZ**

- 1.

In [406]:
import csv
import numpy as np

def read_csv_file(filename):
    '''This function would accept the filename of a csv file and would open the reader and assign it to a list'''
    with open(filename, newline='') as f:
        reader = csv.reader(f)
        data = list(reader)
        print(data)

- 2.

In [407]:
def convert_array(datalist):
    '''This function would accept take a list data structure and slice the list to obtain only its numerical data
    and assigning it to an array'''
    d1 = np.array(datalist)
    d2 = d1[1:,2:7]
    return d2

array = convert_array(data)
array2 = np.vectorize(array)

- 3.

In [416]:
from prettytable import PrettyTable

def table(data):
    '''This function takes the values in the array and puts it into a table format using the PrettyTable library'''
    x = PrettyTable()
    x.field_names = (data[0])
    x.align = 'r'

    for i in range(52):
        x.add_row(data[i+1])
    print(x)

- 4.

In [417]:
y1,y2,y3,y4,y5 = np.hsplit(array,5)

In [418]:
y1 = list(map(int, y1)) 
y2 = list(map(int, y2)) 
y3 = list(map(int, y3)) 
y4 = list(map(int, y4)) 
y5 = list(map(int, y5)) 

year1 = np.array(y1)
year2 = np.array(y2)
year3 = np.array(y3)
year4 = np.array(y4)
year5 = np.array(y5)

In [419]:
y1m = year1.mean()
y2m = year2.mean()
y3m = year3.mean()
y4m = year4.mean()
y5m = year5.mean()

y1mx = year1.max()
y2mx = year2.max()
y3mx = year3.max()
y4mx = year4.max()
y5mx = year5.max()

y1mn = year1.min()
y2mn = year2.min()
y3mn = year3.min()
y4mn = year4.min()
y5mn = year5.min()

In [420]:
y = PrettyTable()
y.field_names = (['Summary Measure','2015','2016','2017','2018','2019'])
y.add_row(['MEAN',f'{y1m:,.2f}',f'{y2m:,.2f}',f'{y3m:,.2f}',f'{y4m:,.2f}',f'{y5m:,.2f}'])
y.add_row(['MAX',f'{y1mx:,.2f}',f'{y2mx:,.2f}',f'{y3mx:,.2f}',f'{y4mx:,.2f}',f'{y5mx:,.2f}'])
y.add_row(['MIN',f'{y1mn:,.2f}',f'{y2mn:,.2f}',f'{y3mn:,.2f}',f'{y4mn:,.2f}',f'{y5mn:,.2f}'])
y.align = 'r'

read_csv_file('africa_pop_data.csv')
convert_array(data)

[['Country', 'Code', '2015', '2016', '2017', '2018', '2019'], ['Algeria', 'DZA', '39728025', '40551404', '41389198', '42228429', '43053054'], ['Angola', 'AGO', '27884381', '28842484', '29816748', '30809762', '31825295'], ['Benin', 'BEN', '10575952', '10872067', '11175204', '11485048', '11801151'], ['Botswana', 'BWA', '2120716', '2159944', '2205128', '2254126', '2303697'], ['Burkina Faso', 'BFA', '18110624', '18646378', '19193284', '19751535', '20321378'], ['Cabo Verde', 'CPV', '524743', '531146', '537497', '543767', '549935'], ['Cameroon', 'CMR', '23298368', '23926539', '24566045', '25216237', '25876380'], ['Central African Republic', 'CAF', '4493170', '4537687', '4596028', '4666377', '4745185'], ['Chad', 'TCD', '14110975', '14561666', '15016773', '15477751', '15946876'], ['Comoros', 'COM', '777424', '795592', '813892', '832322', '850886'], ['Congo, Dem. Rep.', 'COD', '76244544', '78789127', '81398764', '84068091', '86790567'], ['Congo, Rep.', 'COG', '4856095', '4980999', '5110702', '5244363', '5380508'], ["Cote d'Ivoire", 'CIV', '23226143', '23822714', '24437469', '25069229', '25716544'], ['Djibouti', 'DJI', '913993', '929112', '944097', '958920', '973560'], ['Egypt, Arab Rep.', 'EGY', '92442547', '94447072', '96442593', '98423595', '100388073'], ['Equatorial Guinea', 'GNQ', '1168568', '1215179', '1262001', '1308974', '1355986'], ['Eswatini', 'SWZ', '1104044', '1113984', '1124753', '1136191', '1148130'], ['Ethiopia', 'ETH', '100835458', '103603501', '106400024', '109224559', '112078730'], ['Gabon', 'GAB', '1947686', '2007873', '2064823', '2119275', '2172579'], ['Gambia', 'GMB', '2085860', '2149139', '2213894', '2280102', '2347706'], ['Ghana', 'GHA', '27849205', '28481946', '29121471', '29767108', '30417856'], ['Guinea', 'GIN', '11432088', '11738441', '12067539', '12414318', '12771246'], ['Guinea-Bissau', 'GNB', '1737202', '1782437', '1828146', '1874309', '1920922'], ['Kenya', 'KEN', '47878336', '49051686', '50221473', '51393010', '52573973'], ['Lesotho', 'LSO', '2059021', '2075001', '2091412', '2108132', '2125268'], ['Liberia', 'LBR', '4472230', '4586788', '4702228', '4818977', '4937374'], ['Libya', 'LBY', '6418315', '6492164', '6580724', '6678567', '6777452'], ['Malawi', 'MWI', '16745303', '17205289', '17670260', '18143315', '18628747'], ['Mali', 'MLI', '17438778', '17965429', '18512394', '19077690', '19658031'], ['Mauritania', 'MRT', '4046301', '4163534', '4282574', '4403319', '4525696'], ['Mauritius', 'MUS', '1262605', '1263473', '1264613', '1265303', '1265711'], ['Morocco', 'MAR', '34663603', '35126296', '35581294', '36029138', '36471769'], ['Mozambique', 'MOZ', '27042002', '27829942', '28649007', '29495962', '30366036'], ['Namibia', 'NAM', '2314904', '2358041', '2402603', '2448255', '2494530'], ['Niger', 'NER', '20001663', '20788838', '21602472', '22442948', '23310715'], ['Nigeria', 'NGA', '181137448', '185960289', '190873311', '195874740', '200963599'], ['Rwanda', 'RWA', '11369071', '11668818', '11980937', '12301939', '12626950'], ['Sao Tome and Principe', 'STP', '199432', '203227', '207089', '211028', '215056'], ['Senegal', 'SEN', '14578459', '14993528', '15419381', '15854360', '16296364'], ['Seychelles', 'SYC', '93419', '94677', '95843', '96762', '97625'], ['Sierra Leone', 'SLE', '7171914', '7328838', '7488431', '7650154', '7813215'], ['Somalia', 'SOM', '13797201', '14185613', '14589119', '15008154', '15442905'], ['South Africa', 'ZAF', '55386367', '56203654', '57000451', '57779622', '58558270'], ['South Sudan', 'SSD', '10715658', '10832512', '10910759', '10975920', '11062113'], ['Sudan', 'SDN', '38902950', '39847440', '40813396', '41801533', '42813238'], ['Tanzania', 'TZA', '51482633', '53050790', '54663906', '56318348', '58005463'], ['Togo', 'TGO', '7323158', '7509952', '7698475', '7889094', '8082366'], ['Tunisia', 'TUN', '11179949', '11303946', '11433443', '11565204', '11694719'], ['Uganda', 'UGA', '38225453', '39647506', '41162465', '42723139', '44269594'], ['Yemen, Rep.', 'YEM', '26497889', '27168210', '27834821', '28498687', '29161922'], ['Zambia', 'ZMB', '15879361', '16363507', '16853688', '17351822', '17861030'], ['Zimbabwe', 'ZWE', '13814629', '14030390', '14236745', '14439018', '14645468']]

array([['39728025', '40551404', '41389198', '42228429', '43053054'],
       ['27884381', '28842484', '29816748', '30809762', '31825295'],
       ['10575952', '10872067', '11175204', '11485048', '11801151'],
       ['2120716', '2159944', '2205128', '2254126', '2303697'],
       ['18110624', '18646378', '19193284', '19751535', '20321378'],
       ['524743', '531146', '537497', '543767', '549935'],
       ['23298368', '23926539', '24566045', '25216237', '25876380'],
       ['4493170', '4537687', '4596028', '4666377', '4745185'],
       ['14110975', '14561666', '15016773', '15477751', '15946876'],
       ['777424', '795592', '813892', '832322', '850886'],
       ['76244544', '78789127', '81398764', '84068091', '86790567'],
       ['4856095', '4980999', '5110702', '5244363', '5380508'],
       ['23226143', '23822714', '24437469', '25069229', '25716544'],
       ['913993', '929112', '944097', '958920', '973560'],
       ['92442547', '94447072', '96442593', '98423595', '100388073'],
       ['1168568', '1215179', '1262001', '1308974', '1355986'],
       ['1104044', '1113984', '1124753', '1136191', '1148130'],
       ['100835458', '103603501', '106400024', '109224559', '112078730'],
       ['1947686', '2007873', '2064823', '2119275', '2172579'],
       ['2085860', '2149139', '2213894', '2280102', '2347706'],
       ['27849205', '28481946', '29121471', '29767108', '30417856'],
       ['11432088', '11738441', '12067539', '12414318', '12771246'],
       ['1737202', '1782437', '1828146', '1874309', '1920922'],
       ['47878336', '49051686', '50221473', '51393010', '52573973'],
       ['2059021', '2075001', '2091412', '2108132', '2125268'],
       ['4472230', '4586788', '4702228', '4818977', '4937374'],
       ['6418315', '6492164', '6580724', '6678567', '6777452'],
       ['16745303', '17205289', '17670260', '18143315', '18628747'],
       ['17438778', '17965429', '18512394', '19077690', '19658031'],
       ['4046301', '4163534', '4282574', '4403319', '4525696'],
       ['1262605', '1263473', '1264613', '1265303', '1265711'],
       ['34663603', '35126296', '35581294', '36029138', '36471769'],
       ['27042002', '27829942', '28649007', '29495962', '30366036'],
       ['2314904', '2358041', '2402603', '2448255', '2494530'],
       ['20001663', '20788838', '21602472', '22442948', '23310715'],
       ['181137448', '185960289', '190873311', '195874740', '200963599'],
       ['11369071', '11668818', '11980937', '12301939', '12626950'],
       ['199432', '203227', '207089', '211028', '215056'],
       ['14578459', '14993528', '15419381', '15854360', '16296364'],
       ['93419', '94677', '95843', '96762', '97625'],
       ['7171914', '7328838', '7488431', '7650154', '7813215'],
       ['13797201', '14185613', '14589119', '15008154', '15442905'],
       ['55386367', '56203654', '57000451', '57779622', '58558270'],
       ['10715658', '10832512', '10910759', '10975920', '11062113'],
       ['38902950', '39847440', '40813396', '41801533', '42813238'],
       ['51482633', '53050790', '54663906', '56318348', '58005463'],
       ['7323158', '7509952', '7698475', '7889094', '8082366'],
       ['11179949', '11303946', '11433443', '11565204', '11694719'],
       ['38225453', '39647506', '41162465', '42723139', '44269594'],
       ['26497889', '27168210', '27834821', '28498687', '29161922'],
       ['15879361', '16363507', '16853688', '17351822', '17861030'],
       ['13814629', '14030390', '14236745', '14439018', '14645468']],
      dtype='<U24')

In [421]:
table(data)
print(y)

+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|                  Country | Code |      2015 |      2016 |      2017 |      2018 |      2019 |
+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|                  Algeria |  DZA |  39728025 |  40551404 |  41389198 |  42228429 |  43053054 |
|                   Angola |  AGO |  27884381 |  28842484 |  29816748 |  30809762 |  31825295 |
|                    Benin |  BEN |  10575952 |  10872067 |  11175204 |  11485048 |  11801151 |
|                 Botswana |  BWA |   2120716 |   2159944 |   2205128 |   2254126 |   2303697 |
|             Burkina Faso |  BFA |  18110624 |  18646378 |  19193284 |  19751535 |  20321378 |
|               Cabo Verde |  CPV |    524743 |    531146 |    537497 |    543767 |    549935 |
|                 Cameroon |  CMR |  23298368 |  23926539 |  24566045 |  25216237 |  25876380 |
| Central African Republic |  CAF |   4493170 |   4537687 |   4596028 |   4666377 |   4745185 |
|                     Chad |  TCD |  14110975 |  14561666 |  15016773 |  15477751 |  15946876 |
|                  Comoros |  COM |    777424 |    795592 |    813892 |    832322 |    850886 |
|         Congo, Dem. Rep. |  COD |  76244544 |  78789127 |  81398764 |  84068091 |  86790567 |
|              Congo, Rep. |  COG |   4856095 |   4980999 |   5110702 |   5244363 |   5380508 |
|            Cote d'Ivoire |  CIV |  23226143 |  23822714 |  24437469 |  25069229 |  25716544 |
|                 Djibouti |  DJI |    913993 |    929112 |    944097 |    958920 |    973560 |
|         Egypt, Arab Rep. |  EGY |  92442547 |  94447072 |  96442593 |  98423595 | 100388073 |
|        Equatorial Guinea |  GNQ |   1168568 |   1215179 |   1262001 |   1308974 |   1355986 |
|                 Eswatini |  SWZ |   1104044 |   1113984 |   1124753 |   1136191 |   1148130 |
|                 Ethiopia |  ETH | 100835458 | 103603501 | 106400024 | 109224559 | 112078730 |
|                    Gabon |  GAB |   1947686 |   2007873 |   2064823 |   2119275 |   2172579 |
|                   Gambia |  GMB |   2085860 |   2149139 |   2213894 |   2280102 |   2347706 |
|                    Ghana |  GHA |  27849205 |  28481946 |  29121471 |  29767108 |  30417856 |
|                   Guinea |  GIN |  11432088 |  11738441 |  12067539 |  12414318 |  12771246 |
|            Guinea-Bissau |  GNB |   1737202 |   1782437 |   1828146 |   1874309 |   1920922 |
|                    Kenya |  KEN |  47878336 |  49051686 |  50221473 |  51393010 |  52573973 |
|                  Lesotho |  LSO |   2059021 |   2075001 |   2091412 |   2108132 |   2125268 |
|                  Liberia |  LBR |   4472230 |   4586788 |   4702228 |   4818977 |   4937374 |
|                    Libya |  LBY |   6418315 |   6492164 |   6580724 |   6678567 |   6777452 |
|                   Malawi |  MWI |  16745303 |  17205289 |  17670260 |  18143315 |  18628747 |
|                     Mali |  MLI |  17438778 |  17965429 |  18512394 |  19077690 |  19658031 |
|               Mauritania |  MRT |   4046301 |   4163534 |   4282574 |   4403319 |   4525696 |
|                Mauritius |  MUS |   1262605 |   1263473 |   1264613 |   1265303 |   1265711 |
|                  Morocco |  MAR |  34663603 |  35126296 |  35581294 |  36029138 |  36471769 |
|               Mozambique |  MOZ |  27042002 |  27829942 |  28649007 |  29495962 |  30366036 |
|                  Namibia |  NAM |   2314904 |   2358041 |   2402603 |   2448255 |   2494530 |
|                    Niger |  NER |  20001663 |  20788838 |  21602472 |  22442948 |  23310715 |
|                  Nigeria |  NGA | 181137448 | 185960289 | 190873311 | 195874740 | 200963599 |
|                   Rwanda |  RWA |  11369071 |  11668818 |  11980937 |  12301939 |  12626950 |
|    Sao Tome and Principe |  STP |    199432 |    203227 |    207089 |    211028 |    215056 |
|                  Senegal |  SEN |  14578459 |  14993528 |  15419381 |  15854360 |  16296364 |
|               Seychelles |  SYC |     93419 |     94677 |     95843 |     96762 |     97625 |
|             Sierra Leone |  SLE |   7171914 |   7328838 |   7488431 |   7650154 |   7813215 |
|                  Somalia |  SOM |  13797201 |  14185613 |  14589119 |  15008154 |  15442905 |
|             South Africa |  ZAF |  55386367 |  56203654 |  57000451 |  57779622 |  58558270 |
|              South Sudan |  SSD |  10715658 |  10832512 |  10910759 |  10975920 |  11062113 |
|                    Sudan |  SDN |  38902950 |  39847440 |  40813396 |  41801533 |  42813238 |
|                 Tanzania |  TZA |  51482633 |  53050790 |  54663906 |  56318348 |  58005463 |
|                     Togo |  TGO |   7323158 |   7509952 |   7698475 |   7889094 |   8082366 |
|                  Tunisia |  TUN |  11179949 |  11303946 |  11433443 |  11565204 |  11694719 |
|                   Uganda |  UGA |  38225453 |  39647506 |  41162465 |  42723139 |  44269594 |
|              Yemen, Rep. |  YEM |  26497889 |  27168210 |  27834821 |  28498687 |  29161922 |
|                   Zambia |  ZMB |  15879361 |  16363507 |  16853688 |  17351822 |  17861030 |
|                 Zimbabwe |  ZWE |  13814629 |  14030390 |  14236745 |  14439018 |  14645468 |
+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
+-----------------+----------------+----------------+----------------+----------------+----------------+
| Summary Measure |           2015 |           2016 |           2017 |           2018 |           2019 |
+-----------------+----------------+----------------+----------------+----------------+----------------+
|            MEAN |  22,491,651.21 |  23,072,804.02 |  23,664,411.29 |  24,265,356.31 |  24,874,643.13 |
|             MAX | 181,137,448.00 | 185,960,289.00 | 190,873,311.00 | 195,874,740.00 | 200,963,599.00 |
|             MIN |      93,419.00 |      94,677.00 |      95,843.00 |      96,762.00 |      97,625.00 |
+-----------------+----------------+----------------+----------------+----------------+----------------+